image: openjdk:8-jdk

before_script:
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - export JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk-amd64"

stages:
  - test

browserStack:
  stage: test
  image: $CI_REGISTRY/modanisatech/docker-images/node-14-alpine
  script:
    - npm install
    - npm run test:androidBrowserStack
  tags:
    - customer
  artifacts:
    paths:
        - screenshots/
