stages:
  - Test

Test:
  stage: Test
  image: $CI_REGISTRY/modanisatech/docker-images/node-14-alpine
  script:
    - npm install
    - npm run test:androidBrowserStack
  tags:
    - customer
  only:
    - master

