image: registry.gitlab.com/modanisatech/docker-images/flutter/v1-17-1:latest

stages:          # List of stages for jobs, and their order of execution
  - test


unit-test-job:   # This job runs in the test stage.
  stage: test   
  image: $CI_REGISTRY/modanisatech/docker-images/node-14-alpine  # It only starts when the job in the build stage completes successfully.
  script:
    - npm run test:androidBrowserStack
    - sleep 60


